### PR TITLE
Invalid contract created

### PR DESCRIPTION
**Pull request by meevee98**
**Related issue**
#815

**Summary or solution description**
Fixed multiple issues related to calling methods and casting types in-line and importing symbols from different files.
All of them related to not finding imported symbols from different files during code generation.

**How to Reproduce**
From #815:
> **How to Reproduce** 
> The attached zip contains 3 contracts for reproduction.
> 
> 1. Deploy the contract in the folder `1_target_contract` and note the script hash
> 2. Update the contract hash in the file `/2_entry_contract_fails/sample/samplecontract.py` with the hash noted in step 1
> 3. Compile `/2_entry_contract_fails/mycontract.py` , deploy and note the hash
> 4. Call the function `test` on the contract deployed in step 3.
> 
> The 3rd contract in the script is the result of manually building contract using this code
> 
> ```python
>     target_contract = types.UInt160(b"\xb30\xa1\x86\xfa\x05' \x17\r{\x02\xc0\x05\x12B\x8a\xc8\xf5\xd9")
>     sb = vm.ScriptBuilder()
>     sb.emit_dynamic_call(target_contract, "func_no_arg_with_return_boolean")
>     nef = NEF("manual-compiler", script=sb.to_array())
>     with open('manual.nef', 'wb') as f:
>         f.write(nef.to_array())
> ```
> 
> Which works. The side note here is that the result is an Integer instead of Boolean due to #817

**Platform:**
 - OS: Windows 10 x64
 - Python version: Python 3.7

### CODE REVIEW

**Comment by ixje** [comment]
I used the old code from the issue (#815) and recompiled the contracts with the boa version from this pull request. That means I'm still calling this code
```python
    @classmethod
    def func_no_arg_with_return_boolean(cls) -> bool:
        return cast(bool, call_contract(cls._hash, "func_no_arg_with_return_boolean", [], CallFlags.ALL))
```
not the `@contract` interface you showed on Github. With this "old" approach the contract is still invalid. I get this assembly
```
0	OpCode.LDSFLD0
1	OpCode.CALL
3	OpCode.RET
4	OpCode.INITSSLOT
6	OpCode.PUSH1
7	OpCode.NEWARRAY
8	OpCode.STSFLD0
9	OpCode.PUSHDATA1
31	OpCode.DUP
32	OpCode.ISTYPE
34	OpCode.JMPIFNOT
36	OpCode.DUP
37	OpCode.PUSH0
38	OpCode.GE
39	OpCode.ASSERT
40	OpCode.DUP
41	OpCode.SIZE
42	OpCode.PUSHINT8
44	OpCode.OVER
45	OpCode.OVER
46	OpCode.JMPGE
48	OpCode.PUSHDATA1
70	OpCode.REVERSE3
71	OpCode.SUB
72	OpCode.LEFT
73	OpCode.CAT
74	OpCode.JMP
76	OpCode.DROP
77	OpCode.DROP
78	OpCode.CONVERT
80	OpCode.DUP
81	OpCode.SIZE
82	OpCode.PUSHINT8
84	OpCode.NUMEQUAL
85	OpCode.ASSERT
86	OpCode.PUSH0
87	OpCode.DUP
88	OpCode.SIGN
89	OpCode.PUSHM1
90	OpCode.JMPNE 95
92	OpCode.OVER
93	OpCode.SIZE
94	OpCode.ADD
95	OpCode.LDSFLD0
96	OpCode.REVERSE3
97	OpCode.SETITEM
98	OpCode.RET
99	OpCode.INITSLOT
102	OpCode.LDARG0
103	OpCode.RET
104	OpCode.INITSLOT
107	OpCode.NEWARRAY0
108	OpCode.PUSHDATA1
141	OpCode.LDARG0
142	OpCode.PUSH0
143	OpCode.DUP
144	OpCode.SIGN
145	OpCode.PUSHM1
146	OpCode.JMPNE 152
148	OpCode.PUSH2
149	OpCode.PICK
150	OpCode.SIZE
151	OpCode.ADD
152	OpCode.PICKITEM
153	OpCode.SYSCALL System.Contract.Call 0x 
158	OpCode.RET
```
where all it should arguably create is this
```
0	OpCode.NEWARRAY0
1	OpCode.PUSH15
2	OpCode.PUSHDATA1
35	OpCode.PUSHDATA1
57	OpCode.SYSCALL System.Contract.Call 0xb330a186fa052720170d7b02c00512428ac8f5d9 func_no_arg_with_return_boolean
```

**Comment by ixje** [comment]
Using the `@contract` interface with this code works
```python
@contract('0x8523fd34eb6ddc2c3863fc41b7964bcf02a86835')
class SampleContract:
    _hash = UInt160(b"\xb30\xa1\x86\xfa\x05' \x17\r{\x02\xc0\x05\x12B\x8a\xc8\xf5\xd9")

    @staticmethod
    def func_no_arg_with_return_boolean() -> bool:
        pass
```
However, it creates a lot of unnecessary instructions
```
0	OpCode.NEWARRAY0
1	OpCode.PUSH15
2	OpCode.PUSHDATA1
35	OpCode.PUSHDATA1
57	OpCode.SYSCALL System.Contract.Call 0xb330a186fa052720170d7b02c00512428ac8f5d9 func_no_arg_with_return_boolean
62	OpCode.RET
63	OpCode.INITSSLOT
65	OpCode.PUSH1
66	OpCode.NEWARRAY
67	OpCode.STSFLD0
68	OpCode.PUSHDATA1
90	OpCode.DUP
91	OpCode.ISTYPE
93	OpCode.JMPIFNOT
95	OpCode.DUP
96	OpCode.PUSH0
97	OpCode.GE
98	OpCode.ASSERT
99	OpCode.DUP
100	OpCode.SIZE
101	OpCode.PUSHINT8
103	OpCode.OVER
104	OpCode.OVER
105	OpCode.JMPGE
107	OpCode.PUSHDATA1
129	OpCode.REVERSE3
130	OpCode.SUB
131	OpCode.LEFT
132	OpCode.CAT
133	OpCode.JMP
135	OpCode.DROP
136	OpCode.DROP
137	OpCode.CONVERT
139	OpCode.DUP
140	OpCode.SIZE
141	OpCode.PUSHINT8
143	OpCode.NUMEQUAL
144	OpCode.ASSERT
145	OpCode.PUSH0
146	OpCode.DUP
147	OpCode.SIGN
148	OpCode.PUSHM1
149	OpCode.JMPNE 154
151	OpCode.OVER
152	OpCode.SIZE
153	OpCode.ADD
154	OpCode.LDSFLD0
155	OpCode.REVERSE3
156	OpCode.SETITEM
157	OpCode.RET
158	OpCode.INITSLOT
161	OpCode.LDARG0
162	OpCode.RET
```
The first 5 or 6 (depending if the `RET` is really needed) is all we need.

**Review by ixje — CHANGES_REQUESTED** [review]
See my comments above

**Comment by meevee98** [comment]
@ixje the problem in both cases is not exactly that the code is invalid, in those cases the code is not optimized.
the additional opcodes in both cases are related to class access and since we didn't work on opcode optimizations for classes there are some instructions that aren't used in the end

I see this is a problem, but wouldn't it be better to solve it on a different issue?

**Comment by meevee98** [comment]
I have improved some small things, but it still generates some additional code.
I didn't work much on the class-related opcodes because it needs much more attention to make sure that the code is generated when needed

**Comment by ixje** [comment]
Using your last commit at the time of writing this (0334b0b), then compiling the original issue code as mentioned here https://github.com/CityOfZion/neo3-boa/pull/829#issuecomment-1054025873 still produces a faulty contract. It's a lot less code instructions but still not valid
```
0	OpCode.LDSFLD0
1	OpCode.CALL
3	OpCode.RET
4	OpCode.INITSSLOT
6	OpCode.PUSH1
7	OpCode.NEWARRAY
8	OpCode.STSFLD0
9	OpCode.PUSHDATA1
31	OpCode.PUSH0
32	OpCode.LDSFLD0
33	OpCode.REVERSE3
34	OpCode.SETITEM
35	OpCode.RET
36	OpCode.INITSLOT
39	OpCode.LDARG0
40	OpCode.RET
41	OpCode.INITSLOT
44	OpCode.NEWARRAY0
45	OpCode.PUSHDATA1
78	OpCode.LDARG0
79	OpCode.PUSH0
80	OpCode.PICKITEM
81	OpCode.SYSCALL System.Contract.Call 0x 
86	OpCode.RET
``` 
so that should keep #815 unresolved imo, but we can of course merge this PR and build on top of it with other PRs if that's your desired approach

**Comment by ixje** [comment]
> @ixje the problem in both cases is not exactly that the code is invalid, in those cases the code is not optimized. the additional opcodes in both cases are related to class access and since we didn't work on opcode optimizations for classes there are some instructions that aren't used in the end
> 
> I see this is a problem, but wouldn't it be better to solve it on a different issue?

Assuming you are talking about the 2 examples in https://github.com/CityOfZion/neo3-boa/pull/829#issuecomment-1054112526 then yes I agree. The code is indeed valid, but has the unnecessary instructions. Sounds good to track this in another issue.

**Comment by melanke** [comment]
@meevee98  I am merging the PR, let's just not forget to create the necessary issues

**Pull request merged**
